#pragma once
#include <cstdint>
#include <array>
#include <cstring>
#include <type_traits>
#include "../uti/signature.h"
#include "../uti/variant.h"
#include <cstdarg>
#include <vector>
#include <stdlib.h>