#------------------------------------------------------------------------------
# Copyright (c) 2023 John D. Haughton
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#------------------------------------------------------------------------------

import CxxFile

def genTableModule(f,
        symbol,
        func,
        symbol_size,
        size,
        typename,
        prefix,
        fmt
        ):

   f.p(f'const {typename} {symbol}[{symbol_size}] =')
   f.p('{', end = '')

   for i in range(0, size):

      x = i / (size - 1)
      y = func(i, x)

      if i % 8 == 0:
         f.p('\n  ', end = '')

      f.p(f' {prefix}{y:>{fmt}},', end = '')

   f.p('\n};')

def genMulti(
        name,
        bits      = 16,
        include   = "<cstdint>",
        namespace = '',
        log2_size = None,
        size      = None,
        typename  = None,
        prefix    = '',
        fmt       = 'd',
        tables    = [],
       ):
   script      = __file__.split("/")[-1]
   description = f'Auto-generated by \"{script}\"'
   header      = 'Tables_' + name + '.h'
   module      = 'Tables_' + name + '.cpp'

#-------------------------------------------------------------------------------
# Write header

   f = CxxFile.CxxFile(header, description)

   f.p(f'#include {include}');
   f.p()

   if namespace:
      f.p(f'namespace {namespace} {{')
      f.p()

   symbol      = name
   symbol_count = name + '_COUNT'
   symbol_size = name + '_SIZE'
   symbol_mask = name + '_MASK'
   symbol_type = name + '_TYPE'

   if log2_size:
      size = 1 << log2_size

   if not typename:
      typename = f'uint{bits}_t'

   if log2_size:
      f.p(f'static const unsigned {symbol_size}_LOG2 = {log2_size};')
      f.p(f'static const unsigned {symbol_size}      = 1 << {symbol_size}_LOG2;')
      f.p(f'static const unsigned {symbol_mask}      = {symbol_size} - 1;')
   else:
      f.p(f'static const unsigned {symbol_size}      = {size};')
      
   f.p(f'static const unsigned {symbol_count}      = {len(tables)};')

   f.p(f'using {symbol_type} = {typename};')
   f.p()

   for table in tables:
      f.p(f'extern const {typename} {table}[{symbol_size}];')
   
   f.p(f'extern const {typename} *{symbol}[{symbol_count}];')   

   if namespace:
      f.p()
      f.p('}')

#-------------------------------------------------------------------------------
# Write module

   f = CxxFile.CxxFile(module, description)

   f.p(f'#include "{header}"');
   f.p()

   if namespace:
      f.p(f'namespace {namespace} {{')
      f.p()

   for table in tables:
      genTableModule(f,
                     symbol     = table,
                     func      = tables[table],
                     symbol_size = symbol_size,
                     size      = size,
                     typename  = typename,
                     prefix    = prefix,
                     fmt       = fmt,
                     )

   f.p()
   f.p(f'const {typename} *{symbol}[{symbol_count}] = ')   
   f.p('{')
   for table in tables:
      f.p(f'  {table},')
   f.p('};')

   if namespace:
      f.p()
      f.p('}')

def gen(name,
        bits,
        func,
        log2_size = None,
        size      = None,
        typename  = None,
        include   = "<cstdint>",
        prefix    = '',
        namespace = '',
        fmt       = 'd'):

   script      = __file__.split("/")[-1]
   description = f'Auto-generated by \"{script}\"'
   header      = 'Table_' + name + '.h'
   module      = 'Table_' + name + '.cpp'
   symbol      = 'table_' + name
   symbol_size = 'TABLE_' + name.upper() + '_SIZE'
   symbol_mask = 'TABLE_' + name.upper() + '_MASK'
   symbol_type = 'TABLE_' + name.upper() + '_TYPE'

   if log2_size:
      size = 1 << log2_size

   if not typename:
      typename = f'uint{bits}_t'

#-------------------------------------------------------------------------------
# Write header

   f = CxxFile.CxxFile(header, description)

   f.p(f'#include {include}');
   f.p()

   if namespace:
      f.p(f'namespace {namespace} {{')
      f.p()

   if log2_size:
      f.p(f'static const unsigned LOG2_{symbol_size} = {log2_size};')
      f.p(f'static const unsigned {symbol_size}      = 1 << LOG2_{symbol_size};')
      f.p(f'static const unsigned {symbol_mask}      = {symbol_size} - 1;')
   else:
      f.p(f'static const unsigned {symbol_size}      = {size};')
      
   f.p(f'using {symbol_type} = {typename};')

   f.p()
   f.p(f'extern const {typename} {symbol}[{symbol_size}];')

   if namespace:
      f.p()
      f.p('}')

#-------------------------------------------------------------------------------
# Write module

   f = CxxFile.CxxFile(module, description)

   f.p(f'#include "{header}"');
   f.p()

   if namespace:
      f.p(f'namespace {namespace} {{')
      f.p()

   f.p(f'const {typename} {symbol}[{symbol_size}] =')
   f.p('{', end = '')

   for i in range(0, size):

      x = i / (size - 1)
      y = func(i, x)

      if i % 8 == 0:
         f.p('\n  ', end = '')

      f.p(f' {prefix}{y:>{fmt}},', end = '')

   f.p('\n};')

   if namespace:
      f.p()
      f.p('}')